### ISSUE TITLE
SyntaxError: await is only valid in async function

### ISSUE THREAD

**Issue by aravindvnair99** [ehmicky/all-node-versions#5]
# Error:

Following instructions as per the [README](https://github.com/ehmicky/all-node-versions/blob/2d396564672ad4914182c678c111af8f16d2c320/README.md) results in:

```console
SyntaxError: await is only valid in async function
```
# Steps to reproduce:

Following the [README](https://github.com/ehmicky/all-node-versions/blob/2d396564672ad4914182c678c111af8f16d2c320/README.md) is enough:

```console
username@hostname MSYS /d
$ mkdir temp

username@hostname MSYS /d
$ cd temp

username@hostname MSYS /d/temp
$ npm install all-node-versions

added 76 packages, and audited 77 packages in 9s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

username@hostname MSYS /d/temp
$ nano all-node-versions.js
```
And paste:
```js
const allNodeVersions = require('all-node-versions')

const { versions, majors } = await allNodeVersions(options)

console.log(versions)
// ['13.13.0', '13.12.0', ..., '0.1.15', '0.1.14']

console.log(majors)
// [
//   { major: 13, latest: '13.13.0' },
//   { major: 12, latest: '12.16.2', lts: 'erbium' },
//   { major: 11, latest: '11.15.0' },
//   { major: 10, latest: '10.20.1', lts: 'dubnium' },
//   { major: 9, latest: '9.11.2' },
//   { major: 8, latest: '8.17.0', lts: 'carbon' },
//   { major: 7, latest: '7.10.1' },
//   { major: 6, latest: '6.17.1', lts: 'boron' },
//   { major: 5, latest: '5.12.0' },
//   { major: 4, latest: '4.9.1', lts: 'argon' },
//   { major: 0, latest: '0.12.18' }
// ]
```
After saving and exiting:

```console
username@hostname MSYS /d/temp
$ node all-node-versions.js
D:\temp\all-node-versions.js:3

const { versions, majors } = await allNodeVersions(options)
                             ^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by ehmicky** [comment]
Hi @aravindvnair99,

Thanks for reaching out.
I have just fixed the `README` to include an example easier to copy/paste. :+1:

**Comment by aravindvnair99** [comment]
Hey @ehmicky!

It would be better to add `printNodeVersions();` as well.

**Comment by ehmicky** [comment]
The purpose of that example is not really to be copy/pastable, nor run in CLI, but more to show how the library would be used programmatically. I think omitting that additional call might simplify the example a little. Thanks for the feedback though :+1:
